server:
  port: 80801
spring:
  application:
    name: users-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_2023_11_28?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
dubbo:
  application:
    name: users-provider-service
  registry:
    address: zookeeper://10.211.55.9:2181
    timeout: 10000
  metadata-report:
    address: zookeeper://10.211.55.9:2181
  protocol:
    name: dubbo
    port: 20881
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl